### ISSUE TITLE
Wiki page contains unnecessary double-byte spaces

### ISSUE THREAD

**Issue by cx20** [actnwit/RhodoniteTS#1031]
https://github.com/actnwit/RhodoniteTS/wiki/Introduction
![image](https://user-images.githubusercontent.com/1833979/161419015-cd733355-3369-4f96-8a2f-19cea871b433.png)

https://github.com/actnwit/RhodoniteTS/wiki/%E3%82%A4%E3%83%B3%E3%83%88%E3%83%AD%E3%83%80%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3
![image](https://user-images.githubusercontent.com/1833979/161419043-e107c46c-ecd4-4432-a59e-6e8701e6fdcc.png)

**Comment by emadurandal** [comment]
@cx20 Thank you. I'll fix it!
