### ISSUE TITLE
[Rhodonite Editor] Wrong material rendered for VRM model

### ISSUE THREAD

**Issue by infosia** [actnwit/RhodoniteTS#1084]
## Describe the bug

Wrong material rendered for VRM model

### Expected:

![Capture4](https://user-images.githubusercontent.com/1661068/166177461-b7c75f84-b448-40d3-8fc9-6c1ea9712095.PNG)

### Actual:
![Capture3](https://user-images.githubusercontent.com/1661068/166177468-c98700f5-9484-4f57-badc-0769b48feab9.PNG)

## How to reproduce

1. Download [xbot.0.x.vrm](https://github.com/infosia/themachinery-issues/blob/master/0018/xbot.0.x.vrm)
2. Drag & Drop onto https://editor.librn.com/

**Comment by emadurandal** [comment]
@infosia Thank you for the issue.
I'm now investigating this.

**Comment by emadurandal** [comment]
@infosia Now fixed. Please check again: https://editor.librn.com/
![image](https://user-images.githubusercontent.com/3821214/168576194-e112ebda-a1fa-4290-b3ce-a789338a0a98.png)

**Comment by infosia** [comment]
Nice! Yes it's fixed for me too 👍
