### ISSUE TITLE
AlphaBlendModeTest.gltf does not pass test

### ISSUE THREAD

**Issue by cx20** [actnwit/RhodoniteTS#491]
![image](https://user-images.githubusercontent.com/1833979/75109949-68534b00-566b-11ea-966d-16e0327bbf74.png)

Model : https://cx20.github.io/gltf-test/tutorialModels/AlphaBlendModeTest/glTF/AlphaBlendModeTest.gltf

Rn.VERSION
"version: 0.1.5-326-g5607-mod branch: master"

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=750300720)

**Comment by KaYaF** [comment]
I couldn't find the description for the alpha in [the specification](https://www.w3.org/TR/2dcontext/#drawing-images-to-the-canvas) and several web sites. And I couldn't find a parameter of CanvasRenderingContext2D to solve this problem.

To solve the problem, we should take a different approach as required, I think. For example, 
1. Getting the original pixel data by the getImageData
2. Create a resized pixel data
3. Draw the resized pixel data by the putImageData method

**Comment by cx20** [comment]
@KaYaF Here is a link to an article about a similar issue for your reference.
https://zenn.dev/yoya/articles/d874880e1820a5

**Comment by KaYaF** [comment]
@cx20 Thank you for the reference!
The reference fits perfectly with the problem of this issue.

I think it would be better to use a decoder such as PNG.js instead of the getImageData method.

**Comment by emadurandal** [comment]
@cx20 

The WebGL2 version seems to have passed; the WebGPU version is close.

![image](https://github.com/actnwit/RhodoniteTS/assets/3821214/f0a27ba0-bb22-4e7f-bb8e-6b13e6333834)

![image](https://github.com/actnwit/RhodoniteTS/assets/3821214/57c872ad-b383-4250-b8f2-02f5180492ed)

**Comment by cx20** [comment]
I've confirmed that it displays perfectly in WebGL2.
https://cx20.github.io/gltf-test/examples/rhodonite/index.html?category=tutorialModels&model=AlphaBlendModeTest&scale=0.5&type=glTF

This issue will be closed when the WebGPU version passes testing.

![image](https://github.com/actnwit/RhodoniteTS/assets/1833979/3e6b66cd-725e-4db8-9caf-ba1a61ea4eda)

**Comment by cx20** [comment]
I have confirmed that it displays perfectly in the WebGPU version of Rhodonite.

https://cx20.github.io/gltf-test/examples/rhodonite_webgpu/index.html?category=tutorialModels&model=AlphaBlendModeTest&scale=0.5&type=glTF

<img width="1048" alt="image" src="https://github.com/user-attachments/assets/2f461266-2761-404a-886f-080eec004cb9">
