### ISSUE TITLE
The scale of the teacup normal map is not correctly reflected

### ISSUE THREAD

**Issue by cx20** [actnwit/RhodoniteTS#612]
I tried the model of a teacup in the following repository with Rhodonite.
However, I think that Rhodonite does not correctly reflect the normal scale of the teacup.

https://ft-lab.github.io/gltf.html

https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_20.glb
![image](https://user-images.githubusercontent.com/1833979/91868955-4688ef80-ecb0-11ea-9be1-926551a66a8a.png)

|Three.js|Babylon.js|Rhodonite|
|:------:|:------:|:------:|
|![image](https://user-images.githubusercontent.com/1833979/91869224-949df300-ecb0-11ea-8b1e-523c04363abf.png)|![image](https://user-images.githubusercontent.com/1833979/91869246-9d8ec480-ecb0-11ea-953b-114e818d5e0e.png)|![image](https://user-images.githubusercontent.com/1833979/91869264-a41d3c00-ecb0-11ea-99eb-114eb70f85e9.png)|

**Comment by KaYaF** [comment]
@cx20 Could you share us the sample code or sample page of this issue?

**Comment by cx20** [comment]
To display the model, specify `?url=<URL of the model>` after the URL of gltf-test, as shown in the following example.
```
https://cx20.github.io/gltf-test/examples/rhodonite/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_20.glb&scale=15
```

[Three.js + Yunomi_normal_20.glb result:](https://cx20.github.io/gltf-test/examples/threejs/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_20.glb&scale=15)

[Babylon.js + Yunomi_normal_20.glb result:](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_20.glb&scale=15)

[Rhodonite + Yunomi_normal_20.glb result:](https://cx20.github.io/gltf-test/examples/rhodonite/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_20.glb&scale=15)

**Comment by cx20** [comment]
Click the image below to go to the sample URL.

|library|normal 0.5|normal 1.0|normal 2.0|
|:-----:|:-----:|:-----:|:-----:|
|Three.js|[![image](https://user-images.githubusercontent.com/1833979/99108407-9b3ed400-262a-11eb-9e4d-e707bcdf7b00.png)](https://cx20.github.io/gltf-test/examples/threejs/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_05.glb&scale=15)|[![image](https://user-images.githubusercontent.com/1833979/99108476-bb6e9300-262a-11eb-80bb-56f0ce3fd1e1.png)](https://cx20.github.io/gltf-test/examples/threejs/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_10.glb&scale=15)|[![image](https://user-images.githubusercontent.com/1833979/99108489-c32e3780-262a-11eb-8236-7ffc57290119.png)](https://cx20.github.io/gltf-test/examples/threejs/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_20.glb&scale=15)|
|Babylon.js|[![image](https://user-images.githubusercontent.com/1833979/99108521-d0e3bd00-262a-11eb-8461-0d38b1b5e488.png)](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_05.glb&scale=15)|[![image](https://user-images.githubusercontent.com/1833979/99108536-d7723480-262a-11eb-94ae-9196db2f5ba3.png)](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_10.glb&scale=15)|[![image](https://user-images.githubusercontent.com/1833979/99108549-dccf7f00-262a-11eb-8b31-cb6a6e5a1fe0.png)](https://cx20.github.io/gltf-test/examples/babylonjs/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_20.glb&scale=15)|
|Rhodonite|[![image](https://user-images.githubusercontent.com/1833979/99108581-e78a1400-262a-11eb-871d-23849daf18bb.png)](https://cx20.github.io/gltf-test/examples/rhodonite/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_05.glb&scale=15)|[![image](https://user-images.githubusercontent.com/1833979/99108605-efe24f00-262a-11eb-8257-164f2310a077.png)](https://cx20.github.io/gltf-test/examples/rhodonite/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_10.glb&scale=15)|[![image](https://user-images.githubusercontent.com/1833979/99108612-f4a70300-262a-11eb-81cb-f2145d2c7266.png)](https://cx20.github.io/gltf-test/examples/rhodonite/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_20.glb&scale=15)|

**Comment by KaYaF** [comment]
Thanks for the sample page and how to use the parameter of the url.
I can find that the normal is incorrect. I will check this bug.

**Comment by cx20** [comment]
Thank you for working on this issue. I tried again locally with the latest version of Rhodonite.

|library|normal 0.5|normal 1.0|normal 2.0|
|:-----:|:-----:|:-----:|:-----:|
|Rhodonite + Light|![image](https://user-images.githubusercontent.com/1833979/101477570-bfc06e80-3992-11eb-944a-6bf49f8a125c.png)|![image](https://user-images.githubusercontent.com/1833979/101477584-c3ec8c00-3992-11eb-89cb-da3184cd4aec.png)|![image](https://user-images.githubusercontent.com/1833979/101477600-c818a980-3992-11eb-9844-0dbeca875c97.png)|
|Rhodonite + IBL|![image](https://user-images.githubusercontent.com/1833979/101477615-d1097b00-3992-11eb-9e07-7ef2d8713f85.png)|![image](https://user-images.githubusercontent.com/1833979/101477634-d666c580-3992-11eb-9af0-980ee0ed7558.png)|![image](https://user-images.githubusercontent.com/1833979/101477645-dc5ca680-3992-11eb-9a14-ff0bf07049a0.png)|

I can clearly see the difference when using `Directional Lights`, but the difference is subtle when using `IBL`. Is this the expected result?

**Comment by cx20** [comment]
Below are the test results for another test model.

|Library|normal 1.0|normal 10.0|
|:---------:|:---------:|:---------:|
|Rhodonite + Light|![image](https://user-images.githubusercontent.com/1833979/101478855-aae4da80-3994-11eb-9800-e9d9c39d3628.png)|![image](https://user-images.githubusercontent.com/1833979/101478874-afa98e80-3994-11eb-816b-6407b82691a5.png)|
|Rhdonite + IBL|![image](https://user-images.githubusercontent.com/1833979/101478910-b89a6000-3994-11eb-8fe0-9c53172f43b7.png)|![image](https://user-images.githubusercontent.com/1833979/101478930-be904100-3994-11eb-8125-473ddf84db8b.png)|

The model used is the following model published by [glTF-Asset-Generator](https://github.com/KhronosGroup/glTF-Asset-Generator/blob/master/Output/Positive/Material/README.md).

https://github.com/KhronosGroup/glTF-Asset-Generator/blob/master/Output/Positive/Material/Material_01.gltf
https://github.com/KhronosGroup/glTF-Asset-Generator/blob/master/Output/Positive/Material/Material_04.gltf

**Comment by KaYaF** [comment]
Thank you for checking. I only tried the case of "Rhodonite + Light". I will try "Rhodonite + IBL".

**Comment by cx20** [comment]
Please add the following test data to the test.
https://ft-lab.github.io/gltf/normal_map/normal_test_02.glb

Expected result:
![image](https://user-images.githubusercontent.com/1833979/102695337-fa1aed00-4269-11eb-846c-2cd6604229e4.png)
Current result:
![image](https://user-images.githubusercontent.com/1833979/102695348-0a32cc80-426a-11eb-95a6-e5573604f152.png)

**Comment by cx20** [comment]
I tested it again with the latest versions of Rhodonite and IBL. I think the result is very good.

Rhodonite + Yunomi_normal_xx.glb result:

|library|normal 0.5|normal 1.0|normal 2.0|
|:-----:|:-----:|:-----:|:-----:|
|Three.js|[![image](https://user-images.githubusercontent.com/1833979/99108407-9b3ed400-262a-11eb-9e4d-e707bcdf7b00.png)](https://cx20.github.io/gltf-test/examples/threejs/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_05.glb&scale=15)|[![image](https://user-images.githubusercontent.com/1833979/99108476-bb6e9300-262a-11eb-80bb-56f0ce3fd1e1.png)](https://cx20.github.io/gltf-test/examples/threejs/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_10.glb&scale=15)|[![image](https://user-images.githubusercontent.com/1833979/99108489-c32e3780-262a-11eb-8236-7ffc57290119.png)](https://cx20.github.io/gltf-test/examples/threejs/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_20.glb&scale=15)|
|Rhodonite(Before)|[![image](https://user-images.githubusercontent.com/1833979/99108581-e78a1400-262a-11eb-871d-23849daf18bb.png)](https://cx20.github.io/gltf-test/examples/rhodonite/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_05.glb&scale=15)|[![image](https://user-images.githubusercontent.com/1833979/99108605-efe24f00-262a-11eb-8257-164f2310a077.png)](https://cx20.github.io/gltf-test/examples/rhodonite/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_10.glb&scale=15)|[![image](https://user-images.githubusercontent.com/1833979/99108612-f4a70300-262a-11eb-81cb-f2145d2c7266.png)](https://cx20.github.io/gltf-test/examples/rhodonite/index.html?url=https://ft-lab.github.io/gltf/yunomi/Yunomi_normal_20.glb&scale=15)|
|Rhodonite(after)|![image](https://user-images.githubusercontent.com/1833979/103902648-2b3a5f00-513e-11eb-85bd-eb2a77a4d964.png)|![image](https://user-images.githubusercontent.com/1833979/103902664-2f667c80-513e-11eb-9597-a40ad55d19e4.png)|![image](https://user-images.githubusercontent.com/1833979/103902699-3bead500-513e-11eb-9a72-14c28b0dd12f.png)|

Rhodonite + glTF-Asset-Generator / Material_xx.gltf result:
|Library|normal 1.0|normal 10.0|
|:---------:|:---------:|:---------:|
|Rhodonite + Light|![image](https://user-images.githubusercontent.com/1833979/101478855-aae4da80-3994-11eb-9800-e9d9c39d3628.png)|![image](https://user-images.githubusercontent.com/1833979/101478874-afa98e80-3994-11eb-816b-6407b82691a5.png)|
|Rhdonite(before) + IBL|![image](https://user-images.githubusercontent.com/1833979/101478910-b89a6000-3994-11eb-8fe0-9c53172f43b7.png)|![image](https://user-images.githubusercontent.com/1833979/101478930-be904100-3994-11eb-8125-473ddf84db8b.png)|
|Rhodonite(after) + IBL|![image](https://user-images.githubusercontent.com/1833979/103903066-bc113a80-513e-11eb-87ee-0c7b63da9f78.png)|![image](https://user-images.githubusercontent.com/1833979/103903124-d6e3af00-513e-11eb-9598-57abe723caff.png)|

Rhodonite + normal_test_02.glb result:
|Library|result|
|:---------:|:---------:|
|Rhdonite(before)|![image](https://user-images.githubusercontent.com/1833979/102695348-0a32cc80-426a-11eb-95a6-e5573604f152.png)|
|Rhdonite(after)|![image](https://user-images.githubusercontent.com/1833979/103903534-5c675f00-513f-11eb-969c-c491a0d0e2d5.png)|
