### ISSUE TITLE
Texture of BoxTexturedNonPowerOfTwo.gltf is not displayed correctly

### ISSUE THREAD

**Issue by cx20** [actnwit/RhodoniteTS#613]
I tried to display [BoxTexturedNonPowerOfTwo.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxTexturedNonPowerOfTwo).
However, it seems that textures that are not powers of two are not displayed correctly.

Rhodontie + [BoxTextured.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxTextured) result:
![image](https://user-images.githubusercontent.com/1833979/92008788-8ddfb080-ed82-11ea-968c-33bd654921e6.png)

Rhodonite + [BoxTexturedNonPowerOfTwo.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/BoxTexturedNonPowerOfTwo) result:
![image](https://user-images.githubusercontent.com/1833979/92008901-b23b8d00-ed82-11ea-8364-d90f9ed8e97c.png)

**Comment by KaYaF** [comment]
I think this issue is solved by #617.
