### ISSUE TITLE
Loading VC.gltf causes 0 division occurred

### ISSUE THREAD

**Issue by cx20** [actnwit/RhodoniteTS#638]
I tried to view [VC.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/VC) in Rhodonite. However, many error appeared on the console and the model was not displayed.

```javascript
MutableVector3.ts:105 
0 division occurred!
```
-- | -- | -- | --
-- | -- | -- | --
  | divide | @ | MutableVector3.ts:105
  | normalize | @ | MutableVector3.ts:56
  | __updateTargeting | @ | OrbitCameraController.ts:560
  | logic | @ | OrbitCameraController.ts:425
  | $logic | @ | CameraControllerComponent.ts:56
  | process | @ | Component.ts:126
  | process | @ | System.ts:144
  | draw | @ | index.js:102

version: 0.2.6-mod branch: chore/gitignore

**Comment by cx20** [comment]
I noticed that another error occurred before the `0 division occurred`.

[Rhodonite v0.3.2 + VC.gltf result:](https://cx20.github.io/gltf-test/examples/rhodonite/index.html?category=sampleModels&model=VC&scale=0.2&type=glTF)
```
AccessorBase.ts:130 
You are trying to allocate more than you have secured.
takeOne	@	AccessorBase.ts:130
```

The code outputting the error was as follows. Both `__takenCount` and `__count` are `15`.
Perhaps this model has multiple cameras built into it, so it seems to be trapped at the upper limit.

```javascript
if (this.__takenCount >= this.__count) {
    console.error('You are trying to allocate more than you have secured.');
}
```

How can I relax this limit?

**Comment by KaYaF** [comment]
The number of limits of a camera component is specified by [Config.ts](https://github.com/actnwit/RhodoniteTS/blob/b713a61d3743a53abefccb5c727f606e3b85d480/src/foundation/core/Config.ts#L8). I think that you should call  `Rn.Config.maxCameraNumber = (limit number as you want)`, before calling the `system.setProcessApproachAndCanvas` method.

**Comment by cx20** [comment]
@KaYaF  Thanks! I just set `Rn.Config.maxCameraNumber = 20` as per your advice. I think the error has been resolved.

[Rhodonite v0.3.2 + VC.gltf result:](https://cx20.github.io/gltf-test/examples/rhodonite/index.html?category=sampleModels&model=VC&scale=0.2&type=glTF)
