### ISSUE TITLE
Fox.gltf does not animate smoothly

### ISSUE THREAD

**Issue by cx20** [actnwit/RhodoniteTS#641]
I tried animating [Fox.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Fox) with Rhodonite. However, it doesn't seem to animate smoothly.

[Rhodonite + Fox.gltf result](https://cx20.github.io/gltf-test/examples/rhodonite/index.html?category=sampleModels&model=Fox&scale=0.02&type=glTF)
![Fox_002](https://user-images.githubusercontent.com/1833979/94563789-25f98880-02a2-11eb-88ab-eb9b8b2adacb.gif)

|Animation|Second|
|:---:|:---:|
|Survery|3.42|
|Walk|0.71|
|Run|1.16|

The cause is probably that `Rn.AnimationComponent.endInputValue` is the number of seconds in `Survery`.

**Comment by emadurandal** [comment]
@cx20 How about now?

**Comment by cx20** [comment]
Unfortunately, I don't think this has been improved in the latest version.

**Comment by emadurandal** [comment]
@cx20 
Fixed at the version 0.3.18.
Would you check again?

**Comment by cx20** [comment]
Thanks for the fix. I have confirmed that the problem has been resolved in the latest version.
