### ISSUE TITLE
Does Rhodonite not work on Safari for iOS?

### ISSUE THREAD

**Issue by cx20** [actnwit/RhodoniteTS#643]
I tried to view the [gltf-test](https://cx20.github.io/gltf-test/index.html?engines=Three.js,Babylon.js,Filament,PlayCanvas,GLBoost,Rhodonite) Rhodonite sample on iOS14.  However, the screen was blank and nothing was displayed.
Is it because you are using `WebGL2`?

**Comment by cx20** [comment]
I tried to display the following page on iOS14.
https://cx20.github.io/webgl-test/examples/rhodonite/teapot/index.html

When I did remote debugging, I found the following error.

```javascript
[Error] The library does not support this environment because the OES_texture_float_linear is not available
	__getExtension (WebGLContextWrapper.ts:285)
	WebGLContextWrapper (WebGLContextWrapper.ts:39)
	addWebGLContext (WebGLResourceRepository.ts:53:86)
	setProcessApproachAndCanvas (System.ts:179)
	（anonymous関数） (index.js:50)
	fire (jquery-3.4.0.js:3291)
	fireWith (jquery-3.4.0.js:3421)
	done (jquery-3.4.0.js:9523)
	（anonymous関数） (jquery-3.4.0.js:9775)
[Error] The library does not support this environment because the WEBGL_draw_buffers is not available
	__getExtension (WebGLContextWrapper.ts:285)
	WebGLContextWrapper (WebGLContextWrapper.ts:45)
	addWebGLContext (WebGLResourceRepository.ts:53:86)
	setProcessApproachAndCanvas (System.ts:179)
	（anonymous関数） (index.js:50)
	fire (jquery-3.4.0.js:3291)
	fireWith (jquery-3.4.0.js:3421)
	done (jquery-3.4.0.js:9523)
	（anonymous関数） (jquery-3.4.0.js:9775)
[Error] The library does not support this environment because the WEBGL_color_buffer_float is not available
	__getExtension (WebGLContextWrapper.ts:285)
	WebGLContextWrapper (WebGLContextWrapper.ts:47)
	addWebGLContext (WebGLResourceRepository.ts:53:86)
	setProcessApproachAndCanvas (System.ts:179)
	（anonymous関数） (index.js:50)
	fire (jquery-3.4.0.js:3291)
	fireWith (jquery-3.4.0.js:3421)
	done (jquery-3.4.0.js:9523)
	（anonymous関数） (jquery-3.4.0.js:9775)
[Error] WebGL: ERROR: too many uniforms
	compileShader
	createShaderProgram (WebGLResourceRepository.ts:198)
	createProgramAsSingleOperation (Material.ts:465:82)
	setupMaterial (WebGLStrategyUniform.ts:144)
	setupDefaultShaderSemantics (WebGLStrategyUniform.ts:100)
	setupShaderProgram (WebGLStrategyUniform.ts:65)
	$load (WebGLStrategyUniform.ts:181)
	$load (MeshRendererComponent.ts:121)
	process (Component.ts:126)
	process (System.ts:144)
	draw (index.js:133)
	（anonymous関数） (index.js:138)
	fire (jquery-3.4.0.js:3291)
	fireWith (jquery-3.4.0.js:3421)
	done (jquery-3.4.0.js:9523)
	（anonymous関数） (jquery-3.4.0.js:9775)
[Error] TypeError: undefined is not an object (evaluating 'materialNode.shader')
	createProgramAsSingleOperation (Material.ts:422)
	setupMaterial (WebGLStrategyUniform.ts:144)
	setupDefaultShaderSemantics (WebGLStrategyUniform.ts:100)
	setupShaderProgram (WebGLStrategyUniform.ts:71)
	$load (WebGLStrategyUniform.ts:181)
	$load (MeshRendererComponent.ts:121)
	process (Component.ts:126)
	process (System.ts:144)
	draw (index.js:133)
	（anonymous関数） (index.js:138)
	fire (jquery-3.4.0.js:3291)
	fireWith (jquery-3.4.0.js:3421)
	done (jquery-3.4.0.js:9523)
	（anonymous関数） (jquery-3.4.0.js:9775)
```

Is it because iOS doesn't support the following WebGL extensions?
|Extension|
|:----|
|OES_texture_float_linear|
|WEBGL_draw_buffers|
|WEBGL_color_buffer_float|

**Comment by cx20** [comment]
This Teapot sample can be viewed on the MacOS version of Safari, so it doesn't seem to be a WebGL extension issue.

Is it due to the following?
```javascript
WebGL: ERROR: too many uniforms
```

**Comment by KaYaF** [comment]
After the version 0.2.6, it is fixed that the problem of non-supporting OES_texture_float_linear in iOS14.

I think the reason is `too many uniforms`. If you want to use the Rhodonite in a mobile device, you need to use Rn.ProcessApproach.FastestWebGL1 instead of Rn.ProcessApproach.UniformWebGL1 as the argument of the system.setProcessApproachAndCanvas method. In this mode, the rhodonite uses a small number of uniforms.
![image](https://user-images.githubusercontent.com/7972283/96681310-01309680-13b2-11eb-80cf-241eb7c0e946.png)

**Comment by cx20** [comment]
@KaYaF Thanks! I followed your advice and tried changing `UniformWebGL1` to `FastestWebGL1`.
I have now confirmed that [teapot](https://cx20.github.io/webgl-test/examples/rhodonite/teapot/index.html) and [gltf-test](https://cx20.github.io/gltf-test/?engines=Rhodonite) can be viewed on iOS and iPadOS.
