### ISSUE TITLE
[Featurerequest] If the extension is not supported, output a warning to the console.

### ISSUE THREAD

**Issue by cx20** [actnwit/RhodoniteTS#644]
Currently, loading a model with a glTF extension that Rhodonite does not support will result in an error.
I think it's better to print to the console that the extension isn't supported, not an error.

Below are examples of other libraries.
|Library|Message|Output|
|:----:|:----|:----:|
|three.js|THREE.GLTFLoader: Unknown extension "FAKE_materials_quantumRendering".|console|
|Babylon.js|Require extension FAKE_materials_quantumRendering is not available|display|

**Comment by emadurandal** [comment]
@cx20 thanks. we'll do something.

**Comment by emadurandal** [comment]
Done at 9aca38b259a3f2743e1134801131ca59118b3cd0
