### ISSUE TITLE
[Featurerequest] KHR_materials_variants

### ISSUE THREAD

**Issue by cx20** [actnwit/RhodoniteTS#655]
[KHR_materials_variants](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_materials_variants/README.md) is a glTF extension that allows you to switch between several different variants of materials in a single model.

See below for use cases.
https://www.khronos.org/blog/streamlining-3d-commerce-with-material-variant-support-in-gltf-assets

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=750298009)

**Comment by emadurandal** [comment]
Nice! We'll support this!

**Comment by emadurandal** [comment]
@cx20 Current Rhodonite already support KHR_materials_variants!
![image](https://user-images.githubusercontent.com/3821214/203357219-0fb8c131-7e5c-4fa0-8439-b6e84f00cca2.png)

**Comment by cx20** [comment]
@emadurandal Thanks. I tried the `KHR_materials_variants` extension with the gltf-test Rhdoonite sample.
https://cx20.github.io/gltf-test/examples/rhodonite/index.html?category=tutorialModels&model=MaterialsVariantsShoe&scale=10&type=glTF

![image](https://user-images.githubusercontent.com/1833979/203871481-ecd35939-2d35-4c4b-a742-d20d471d171f.png)
