### ISSUE TITLE
The "set alphaMode" in material.ts does not work

### ISSUE THREAD

**Issue by KaYaF** [actnwit/RhodoniteTS#670]
I changed an alpha mode in material manually. However, the result is strange. 

In the following image, all the material must be opaque. However, The result is "blend" or "cut" mode.
![image](https://user-images.githubusercontent.com/7972283/100711698-02170800-33f5-11eb-9a6f-1392988656a8.png)

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=750297947)

**Comment by KaYaF** [comment]
The cause is that an alpha mode is embedded in the shader.

**Comment by emadurandal** [comment]
The solution must be to use a shader parameter for switching alpha mode dynamically.

**Comment by KaYaF** [comment]
Considering the performance and user-friendliness, it would be better to add one more dynamic alpha mode to the current three static alpha modes.

Note that there is no performance improvement at this time due to [the presence of "discard" in the wireframe process](https://github.com/actnwit/RhodoniteTS/blob/859315abba3e305afe797666289812dc29c6fe[…]rc/webgl/shaderity_shaders/PbrSingleShader/PbrSingleShader.frag).

**Comment by emadurandal** [comment]
In current version, changing the alphaMode was addressed by forcing the shaders to recompile.
