### ISSUE TITLE
glTFs that use OrthographicCamera do not appear

### ISSUE THREAD

**Issue by kmd09** [actnwit/RhodoniteTS#701]
I tried to display a glTF that uses OrthographicCamera, but it did not show up. 

## To Reproduce

A combination of [Cameras.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Cameras) and [RhodoniteEditor](https://editor.librn.com/) can reproduce the problem.
Cameras.gltf defines both PerspectiveCamera("camera": 0) and OrthographicCamera("camera": 1), so you need to select OrthographicCamera in the editor.

## Expected (Render with [BabylonSandbox](https://sandbox.babylonjs.com/))
<img width="400" alt="Screen Shot 2021-02-09 at 21 00 58" src="https://user-images.githubusercontent.com/5725274/107471057-ceecb400-6baf-11eb-9585-c94beea3c1f9.png">

## Actual (Render with [RhodoniteEditor](https://editor.librn.com/))
<img width="400" alt="Screen Shot 2021-02-09 at 21 02 07" src="https://user-images.githubusercontent.com/5725274/107471202-183d0380-6bb0-11eb-9129-65eb853ddc5a.png">

## Already tried
I tried to display the Cameras.gltf against the Rhodonite Editor as of last September, and found the same problem. The commit hash i tried is `2e1b2b47565b7e4648383ff37c2f7a53cab0c950`. This leads us to believe that the problem is not a recent one.

**Comment by kmd09** [comment]
Correcting the line in the URL fixed the problem. I'll send out a PR.
https://github.com/vrize/RhodoniteTS/blob/alpha/master/src/foundation/importer/ModelConverter.ts#L457

**Comment by cx20** [comment]
I have updated `Rhodonite` in [gltf-test](https://github.com/cx20/gltf-test) and confirmed that this problem has been resolved.

[Rhodonite + Cameras.gltf result:](https://cx20.github.io/gltf-test/examples/rhodonite/index.html?category=tutorialModels&model=Cameras&scale=1&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/108210540-025eae00-716f-11eb-85bb-fb7257899226.png)
