### ISSUE TITLE
Support the shader editing of the spector.js

### ISSUE THREAD

**Issue by emadurandal** [actnwit/RhodoniteTS#709]
https://github.com/BabylonJS/Spector.js/blob/master/documentation/extension.md#shader-editor

Thank cx20 for the infomation!

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=750297802)

**Comment by emadurandal** [comment]
Now Working with https://github.com/actnwit/RhodoniteTS/pull/939
It seems to require an HTTPS connection.

![image (2)](https://user-images.githubusercontent.com/3821214/147514111-439d8ad3-89e1-4bf7-810e-c017828a5008.png)

**Comment by cx20** [comment]
I have confirmed that it works.
https://cx20.github.io/gltf-test/examples/rhodonite/index.html?category=sampleModels&model=Duck&scale=1&type=glTF
![image](https://user-images.githubusercontent.com/1833979/147639515-98133730-a3c5-4518-a748-8d84506aaf93.png)
