### ISSUE TITLE
Lantern.gltf is not displayed correctly when in KHR_mesh_quantization format

### ISSUE THREAD

**Issue by cx20** [actnwit/RhodoniteTS#720]
I tried to display the [KHR_mesh_quantization](https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Khronos/KHR_mesh_quantization) version of [Lantern.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Lantern) in Rhodonite.
However, it seems that fine grains are displayed.

|glTF|glTF-Quantized|
|:---:|:---:|
|[![image](https://user-images.githubusercontent.com/1833979/110323501-06883800-8058-11eb-82ca-1331501271f1.png)](https://cx20.github.io/gltf-test/examples/rhodonite/index.html?category=tutorialModels&model=Lantern&scale=0.06&type=glTF)|[![image](https://user-images.githubusercontent.com/1833979/110323532-0e47dc80-8058-11eb-9eb7-2e54daf69aa7.png)](https://cx20.github.io/gltf-test/examples/rhodonite/index.html?category=tutorialModels&model=Lantern&scale=0.06&type=glTF-Quantized)|

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=750297756)

**Comment by emadurandal** [comment]
We need to support KHR_mesh_quantization for it.

**Comment by emadurandal** [comment]
Currently supported

![image](https://github.com/actnwit/RhodoniteTS/assets/3821214/f5801528-1509-43c8-bb60-9648c926e95a)
