### ISSUE TITLE
In Safari, MetalRoughSpheres.gltf looks like a soccer ball

### ISSUE THREAD

**Issue by cx20** [actnwit/RhodoniteTS#723]
I tried viewing [MetalRoughSpheres.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MetalRoughSpheres) in Rhodonite on Safari.
However, some spheres appear as polyhedra, like soccer balls.

Safari + Rhdonite FastestWebGL1 mode result:
![image](https://user-images.githubusercontent.com/1833979/110471509-8e854500-811f-11eb-819d-84ebb1ee61b6.png)

Safari + Rhdonite FastestWebGL2 mode result:
![image](https://user-images.githubusercontent.com/1833979/110472390-a6a99400-8120-11eb-8b2b-45a2411a875c.png)

This seems to be related to a [known issue](https://bugs.chromium.org/p/chromium/issues/detail?id=479753) in Safari.
In the near future, `ANGLE` will be adopted in Safari's WebGL backend, so we need to test it again at that time.

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=750297738)

**Comment by cx20** [comment]
Safari TP 124 seems to have solved this problem.

**Comment by cx20** [comment]
https://clara.io/view/2c6e0419-0113-477c-9101-653571eb0309/webgl
|OS                |Browser           |WebGL via Metal|result:           |Renderer          |
|:-----------------|:-----------------|:-------------:|:----------------:|:-----------------|
|iOS 15            |Safari 15.0       |     true      |:white_check_mark:|Apple GPU         |
|iOS 15            |Safari 15.0       |     false     |:white_check_mark:|Apple GPU         |
|iPadOS 15         |Safari 15.0       |     true      |:white_check_mark:|Apple GPU         |
|iPadOS 15         |Safari 15.0       |     false     |:white_check_mark:|Apple GPU         |
|macOS Big Sur 11.6|Safari 15.0       |     true      |:white_check_mark:|ANGLE (Metal Renderer: Intel(R) UHD Graphics 617)             |
|macOS Big Sur 11.6|Safari 15.0       |     false     |:x:               |ANGLE (Intel Inc., Intel(R) UHD Graphics 617, OpenGL 4.1 core)|
|macOS Big Sur 11.6|Safari 15.4 TP 132|     true      |:white_check_mark:|ANGLE (Metal Renderer: Intel(R) UHD Graphics 617)             |
|macOS Big Sur 11.6|Safari 15.4 TP 132|     false     |:x:               |ANGLE (Intel Inc., Intel(R) UHD Graphics 617, OpenGL 4.1 core)|

**Comment by emadurandal** [comment]
@cx20 Much time has passed, but how is the situation now?　I would like to close if the problem has been resolved.

**Comment by cx20** [comment]
I have confirmed that the problem does not occur in the following environment. Perhaps this issue can be closed.

macOS Ventura 13.0.1 + Safari 16.1
macOS Ventura 13.0.1 + Safari 16.4 TP 158
