### ISSUE TITLE
Incorrect colors when using multiple Directional Lights

### ISSUE THREAD

**Issue by cx20** [actnwit/RhodoniteTS#745]
I have tried multiple `Directional Lights` with the latest version of Rhodonite.
However, the colors do not seem to be correct. I think it was correct in the old version.

[Rhodonite v0.2.6 result:](https://rawcdn.githack.com/cx20/webgl-test/bf353601b746ac195b5668811dc3a6d3786cc82b/examples/rhodonite/complex/index.html)
![image](https://user-images.githubusercontent.com/1833979/112486783-8b48b500-8dbf-11eb-80e2-db6818e1cc5d.png)

[Rhodonite v0.3.15 result:](https://cx20.github.io/webgl-test/examples/rhodonite/complex/index.html)
![image](https://user-images.githubusercontent.com/1833979/112486806-8f74d280-8dbf-11eb-9016-8252cb343d71.png)

**Comment by emadurandal** [comment]
The problem did not occur until 0.3.1, and was confirmed to occur in 0.3.7.

**Comment by KaYaF** [comment]
I think this problem has been solved by the above PR.

**Comment by cx20** [comment]
@KaYaF Thanks! I've confirmed that the latest version (I don't know what to call it, but tentatively call it v0.3.19dev) fixes this issue.

Rhodonite v0.3.19dev result:
![image](https://user-images.githubusercontent.com/1833979/114890807-4eb02c80-9e46-11eb-9420-48f78f647956.png)

**Comment by KaYaF** [comment]
@cx20 Good! Thanks for your trying!

I think the hash of the commit is useful to specify the exact version(commit). In this case, the hash is `f75e0c1fdb5fe55c64fbc85c884b27915ca0638e`. If you write the full hash here directory(I wrote the left full hash in code space), we can jump to the commit page like here f75e0c1fdb5fe55c64fbc85c884b27915ca0638e.


How to get the full hash

1. open commits of a branch
![image](https://user-images.githubusercontent.com/7972283/114988563-6c76a380-9ed1-11eb-863f-fbb5eed6d36d.png)

2. find a commit to specify
![image](https://user-images.githubusercontent.com/7972283/114988175-fd00b400-9ed0-11eb-89e6-cbff0bfdeac5.png)

**Comment by cx20** [comment]
@KaYaF  Thanks! I understand about hashes.
What should I call the next version? 
I would like to know the name of the version, because I have listed the version name of the library in [gltf-test](https://github.com/cx20/gltf-test/).

![image](https://user-images.githubusercontent.com/1833979/115020057-fa17ba80-9ef4-11eb-99ac-da51b2009a58.png)

**Comment by KaYaF** [comment]
@cx20 I have two ideas.
1. Wait for the next version. This is the simplest solution, I think. The next version will publish within a month.
2. Use the short hash. You can get the current version by Rn.VERSION from the console. In this case, the example of the version is "RhodoniteTS v0.3.19dev-f75e0c1".
![image](https://user-images.githubusercontent.com/7972283/115034767-d52c4300-9f06-11eb-8fc5-072846add736.png)

**Comment by cx20** [comment]
@KaYaF  Thank you for telling me your ideas.
Since it is long to display the `version` + `hash value`, I would like to list only the `version` in gltf-test.

Other libraries may refer to the development version as `xxx-dev` / `xxx-rc` / `xxx-alpha`.
If you guys are okay with calling it `v0.3.19dev`, I'd like to list it in [gltf-test](https://github.com/cx20/gltf-test) under that name.

And when reporting an issue, I would like to add a hash value to clarify the version.

**Comment by KaYaF** [comment]
@cx20 Indeed, `version` + `hash value` is a long name.
I think the notation `v0.3.19dev` is also fine. If someone want to know the detailed version, they can easily find it on the sample page using Rn.VERSION.

It would be very helpful if you could include the value of hash or result of the Rn.VERSION. Thanks!
