### ISSUE TITLE
Improved usability of AbstractShaderNode.addInputConnection method

### ISSUE THREAD

**Issue by KaYaF** [actnwit/RhodoniteTS#754]
[The second and third arguments of AbstractShaderNode.addInputConnection method are strings](https://github.com/actnwit/RhodoniteTS/blob/86a3564bda4c74fedc9786c8c499eee5159d1985/src/foundation/materials/core/AbstractShaderNode.ts#L79-L80). This makes it easy to get the specification wrong. I think we need to change the specification of the arguments to be more user friendly.

In my opinion, the WebAPI AudioNode may be helpful.

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=750297605)

**Comment by emadurandal** [comment]
In current version, the arguments is now new Socket object.
The type checking is also effective.

![image](https://github.com/actnwit/RhodoniteTS/assets/3821214/4fdc48db-e0bb-4930-b3e6-7f71678089b9)
