### ISSUE TITLE
WEBGL_compressed_texture_astc error is output to the console

### ISSUE THREAD

**Issue by cx20** [actnwit/RhodoniteTS#764]
I have tried Rhodonite v0.3.19dev in a Windows environment.
However, it seems that the error of `WEBGL_compressed_texture_astc` extension is output to the console.

https://cx20.github.io/gltf-test/examples/rhodonite/index.html?category=tutorialModels&model=AlphaBlendModeTest&scale=0.5&type=glTF

```javascript
rhodonite.min.js:1
The library does not support this environment because the WEBGL_compressed_texture_astc is not available
__getExtension @ rhodonite.min.js:1
p @ rhodonite.min.js:1
addWebGLContext @ rhodonite.min.js:1
setProcessApproachAndCanvas @ rhodonite.min.js:1
load @ index.js:53
async function (async)
load @ index.js:49
load (async)
(anonymous) @ index.js:341
```

This extension is only available in certain environments. It is better not to make an error because this extension is not available in Windows environments.

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=750297526)

**Comment by emadurandal** [comment]
Currently, Those are now warning, not error actually.
![image](https://user-images.githubusercontent.com/3821214/120425598-7a14b980-c3a9-11eb-9569-66fb2dad53d9.png)

But certainly, It looks better to change them to 'info' output than 'warn'.

**Comment by emadurandal** [comment]
@cx20 Since 01443f9d48726029abb5d1a69c8d13e71365a2c7, those warning-level messages are now info-level messages.
This change would have made the console much cleaner and improved the psychological safety of users.
![image](https://github.com/actnwit/RhodoniteTS/assets/3821214/b3079056-52ce-4b62-8cf6-c1d5d7226fa7)
