### ISSUE TITLE
RecursiveSkeletons.gltf does not display as expected

### ISSUE THREAD

**Issue by cx20** [actnwit/RhodoniteTS#770]
I tried to display the following model in Rhodonite.
https://github.com/vpenades/glTF-Sample-Models/tree/master/2.0/RecursiveSkeletons
However, it does not seem to be displayed correctly.

Expected results:
![image](https://user-images.githubusercontent.com/1833979/117545205-c21d1680-b05f-11eb-8053-615f1a53dcc3.png)

[Rhodonite + RecursiveSkeletons.gltf result](https://cx20.github.io/gltf-test/examples/rhodonite/index.html?category=tutorialModels&model=RecursiveSkeletons&scale=0.01&type=glTF):
![image](https://user-images.githubusercontent.com/1833979/117545293-16c09180-b060-11eb-9632-e5005148ecb2.png)

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=750297430)

**Comment by emadurandal** [comment]
The current version supports RecursiveSkeletons.gltf properly.

![image](https://github.com/actnwit/RhodoniteTS/assets/3821214/0788f496-efe6-4e78-baf6-9e55733dd754)
