### ISSUE TITLE
When I ran "npm build run", I got "Module not found: Error:".

### ISSUE THREAD

**Issue by ishiiyuki** [actnwit/RhodoniteTS#775]
When I tried to run "npm build run" in my local environment to see how v0.3.21 works, I got the following error.
Can you tell me how to deal with it?

<details>
<summary>エラー内容</summary>
ERROR in ./src/xr/WebXRInput.ts 11:22-105
Module not found: Error: Can't resolve 'webxr-input-profiles/packages/registry/profiles/oculus/oculus-touch.json' in 'D:\Rhodonite\RhodoniteTS\src\xr'
resolve 'webxr-input-profiles/packages/registry/profiles/oculus/oculus-touch.json' in 'D:\Rhodonite\RhodoniteTS\src\xr'
  Parsed request is a module
  using description file: D:\Rhodonite\RhodoniteTS\package.json (relative path: ./src/xr)
    resolve as module
      D:\Rhodonite\RhodoniteTS\src\xr\node_modules doesn't exist or is not a directory
      D:\Rhodonite\RhodoniteTS\src\node_modules doesn't exist or is not a directory
      looking for modules in D:\Rhodonite\RhodoniteTS\node_modules
        existing directory D:\Rhodonite\RhodoniteTS\node_modules\webxr-input-profiles
          using description file: D:\Rhodonite\RhodoniteTS\node_modules\webxr-input-profiles\package.json (relative path: .)
            using description file: D:\Rhodonite\RhodoniteTS\node_modules\webxr-input-profiles\packages\registry\package.json (relative path: ./profiles/oculus/oculus-touch.json)
              no extension
                D:\Rhodonite\RhodoniteTS\node_modules\webxr-input-profiles\packages\registry\profiles\oculus\oculus-touch.json doesn't exist
              .ts
                D:\Rhodonite\RhodoniteTS\node_modules\webxr-input-profiles\packages\registry\profiles\oculus\oculus-touch.json.ts doesn't exist
              .js
                D:\Rhodonite\RhodoniteTS\node_modules\webxr-input-profiles\packages\registry\profiles\oculus\oculus-touch.json.js doesn't exist
              as directory
                D:\Rhodonite\RhodoniteTS\node_modules\webxr-input-profiles\packages\registry\profiles\oculus\oculus-touch.json doesn't exist
      D:\Rhodonite\node_modules doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
 @ ./src/xr/WebXRSystem.ts 11:0-119 331:12-25 358:37-59 439:49-68 441:28-55
 @ ./src/index.ts 98:0-44 219:17-29
</details>

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=750297332)

**Comment by ishiiyuki** [comment]
When I used "yarn", I didn't get the error anymore.

**Comment by ishiiyuki** [comment]
I was able to deal with this by updating npm itself, but
If I don't add --save --legacy-peer-deps, I get an error.

**Comment by KaYaF** [comment]
I have also seen the same error.
My environment is a Mac mini with M1.

Here is my result.
◯ : yarn install -> yarn build
◯ : yarn install -> npm run build
×: npm install -> yarn build
×: npm install -> npm run build

◯ means no error. × means that I got the error like
```
Can't resolve 'webxr-input-profiles/packages/registry/profiles/oculus/oculus-touch.json' in 'D:\Rhodonite\RhodoniteTS\src\xr' 
```


I have checked the node_modules/webxr-input-profiles folder. The content seems to be different after running yarn install and after running npm install. I don't know why, but after npm install, the webxr-input-profiles/packages/registry/profiles/oculus/oculus-touch.json required by src/xr/WebXRInput.ts does not exist.

This is the case after yarn install.
![image](https://user-images.githubusercontent.com/7972283/118429045-c0acb780-b70b-11eb-95cc-b96b30d2dc2d.png)


This is the case after npm install.
![image](https://user-images.githubusercontent.com/7972283/118428872-58f66c80-b70b-11eb-9245-579603ad6779.png)

**Comment by emadurandal** [comment]
@ishiiyuki @KaYaF As I told you on other place, It looks something about yarn.lock/package-lock.json files.
I added yarn.lock to master and recommendation of using yarn to README.md.

I'll close this issue at this time if you don't mind. Is it OK with you?
