### ISSUE TITLE
Change calculation method of spring bone

### ISSUE THREAD

**Issue by KaYaF** [actnwit/RhodoniteTS#820]
Compare [this part](https://github.com/actnwit/RhodoniteTS/blob/9b3a9e8c65813cb0af22597fefc7b098a49255f1/src/foundation/physics/VRMSpringBonePhysicsStrategy.ts) with [spring bone calculation in VRM](
https://github.com/vrm-c/UniVRM/blob/7b0c8f5f97a39a54a7537f2093224b66a6e85778/Assets/VRM/Runtime/SpringBone/VRMSpringBone.cs)

┆Issue is synchronized with this [Wrike Item](https://www.wrike.com/open.htm?id=750296887)

**Comment by emadurandal** [comment]
@KaYaF I fixed the behavior of Spring bone at https://github.com/actnwit/RhodoniteTS/pull/1217
![image](https://user-images.githubusercontent.com/3821214/206856670-b171b932-06c1-4390-b62b-1c0518ded959.png)
