### ISSUE TITLE
The constructor of the MutableScalar class is invalid

### ISSUE THREAD

**Issue by KaYaF** [actnwit/RhodoniteTS#935]
If we input a type other than TypedArray in the constructor of MutableScalar, this._v does not become a typed array and an error occurs.

https://github.com/actnwit/RhodoniteTS/blob/d89534a82bfadcd2ab0999cf7616be3b3c8f35d6/src/foundation/math/MutableScalar.ts#L7

https://github.com/actnwit/RhodoniteTS/blob/d89534a82bfadcd2ab0999cf7616be3b3c8f35d6/src/foundation/math/MutableScalar.ts#L47

https://github.com/actnwit/RhodoniteTS/blob/d89534a82bfadcd2ab0999cf7616be3b3c8f35d6/src/foundation/math/MutableScalar.ts#L73

![image](https://user-images.githubusercontent.com/7972283/147225741-581e6a6e-f80d-40d4-9a0f-fe7b30b02c9f.png)

**Comment by emadurandal** [comment]
Fixed at https://github.com/actnwit/RhodoniteTS/pull/941
