### ISSUE TITLE
Support KHR_materials_clearcoat extension

### ISSUE THREAD

**Issue by emadurandal** [actnwit/RhodoniteTS#946]
## References
- https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_materials_clearcoat/README.md

**Comment by cx20** [comment]
I checked if the Clear Coat extension was implemented in Rhodonite `v0.7.1`.
I confirmed that all the rightmost columns passed.
`UV0` and `UV1` don't seem to pass the test, but I don't know what's causing it.

|Rhodonite version|TextureTransformMultiTest.gltf|
|:----:|:-----------:|
|Rhodonite v0.7.0|[![image](https://user-images.githubusercontent.com/1833979/166716147-c44c217c-3203-477b-9f1b-5a39a4a86da7.png)](https://rawcdn.githack.com/cx20/gltf-test/991317f0072ff77d9a20e9c2eb0b5ca4840810d7/examples/rhodonite/index.html?category=tutorialModels&model=TextureTransformMultiTest&scale=1&type=glTF)|
|Rhodonite v0.7.1|[![image](https://user-images.githubusercontent.com/1833979/166716194-73619eed-4a50-4ab0-a6a7-2633de280d37.png)](https://rawcdn.githack.com/cx20/gltf-test/6fc373373dece63867af190e517cdf5ede57a7b7/examples/rhodonite/index.html?category=tutorialModels&model=TextureTransformMultiTest&scale=1&type=glTF)|

**Comment by emadurandal** [comment]
@cx20 I fixed the problem completely at https://github.com/actnwit/RhodoniteTS/pull/1189
![image](https://user-images.githubusercontent.com/3821214/194379853-30e89ff4-e560-42f7-9919-440b8c812891.png)
